### ISSUE TITLE
will xport convert Cport files to csv?

### ISSUE THREAD

**Issue by telljmc** [selik/xport#103] opened 2023-01-12 00:42 UTC
I have what I believe are some Cport files.  I need to convert them to csv.  Based on the documentation I anticipated that xport would enable me to do that.  I tried "loading" them by following your examples.  However, I receive the following error message, "Document does not match SAS Version 5 or 6 Transport (XPORT) format".  I have attached one of the files.  Am I mistaken as to the format?  or xport's ability to convert them?
[C2214O5P.zip](https://github.com/selik/xport/files/10397080/C2214O5P.zip)

**Comment by selik** [comment] 2023-03-23 22:37
Unfortunately, CPORT is not only proprietary, but completely closed. There's no public information about how the file format works. If we had a few Rosetta stone documents, we might be able to reverse engineer it, but it'd be non-trivial.

**Comment by selik** [comment] 2023-03-23 22:37
Closing as a duplicate of #6

**Closed by selik** 2023-03-23 22:37 UTC
