### ISSUE TITLE
having issues while setting metadata

### ISSUE THREAD

**Issue by alfred-b-chan** [selik/xport#49] opened 2020-07-09 03:52 UTC
Code extract
ds = xport.Dataset(table_df, name='Data', label='Test data')
for column, variable in ds.items():
     if (a_condition):
           v.format="10.2"

with open('my_file.xpt', 'wb') as f:
      xport.v56.dump(ds,f)  

That would give me an error when opening my_file.xpt.  And a_condition is true when column is numeric.

Please assist and can you please have more examples on the export.

**Comment by selik** [comment] 2020-07-10 21:23
@alfred-b-chan I'll take a look this weekend.

**Comment by selik** [comment] 2020-07-15 17:26
Hi @alfred-b-chan, I couldn't reproduce your error. Could you paste the error message you saw here?

**Comment by alfred-b-chan** [comment] 2020-07-15 22:09
Format is exposed as property.  But the following way of setting will break.  For instance, once file is generated, I cannot open from SAS system Viewer 9.1.

for column, variable in xport_dataset.items():
	
	variable.label = 'my label'  # this works 

	#target_type = column_metadata['target_type'].item()
	target_length = 10
	#
	# if target_type.strip().lower() == "char":
	#     variable_format = f'${target_length}.'
	# else:
	#     variable_format = f'{target_length}.'
	# variable.format = variable_format   # this does NOT work 

	object.__setattr__(variable, 'width', 10)  # this works

Also can you please expose all metadata as properties such as vtype, width, _format. 

Thanks

**Comment by selik** [comment] 2020-07-15 22:26
> vtype, width, _format.

This module currently supports (or attempts to support) everything from SAS's published file format description for [XPORT v5](https://support.sas.com/techsup/technote/ts140.pdf). For variable metadata, you can see a brief explanation of what the file format can contain in the code comments: https://github.com/selik/xport/blob/04aca9360707a120c9ed410b4fe081b046c61375/src/xport/v56.py#L51

I'm guessing by "vtype" you mean the variable type. That can only be either Numeric or Character, so I infer that from the Python data type. Does that not work for you?

You can set "width" by the `length` property. Or do you mean something other than the field length?

By "_format" do you mean the format or informat? Both of those are supported.

> I cannot open from SAS system Viewer 9.1

Can you tell me the error message?

Unfortunately, I use a Mac and can't run SAS System Viewer. I know JMP provides a free 30-day trial, and it looks like I could create XPT files with JMP, so I could do some debugging with it for a short time.

What would really help is an example of a valid XPT file that has the format you'd like.

**Comment by alfred-b-chan** [comment] 2020-07-22 13:40
thanks..  i end up converting the dataframe datatype before i call the xport.Dataset constructor....  btw, how to handle null?
for instance, my column in dataframe is numeric and some rows are null.. i  convert them to None

df[my_numeric_col] = df[my_numeric_col].where(pd.notnull(df[my_numeric_col]), None)  # this works

When I call the xport.Dataset constructor, it seems those rows with None ends up being a dash instead of a period in SAS System viewer.  

It seems a period is supposed to be a null in SAS System Viewer..  so what should i set in order to show a period (which indicates a null) in SAS System viewer?   thanks

**Comment by selik** [comment] 2020-07-22 13:58
You should use NaN instead of None for numeric nulls. I'm surprised you were even able to get a Nine in there, because Pandas usually converts those to NaN for a float column.

**Comment by alfred-b-chan** [comment] 2020-07-22 14:09
when debugging it, i could see the column 'empty' and it showed NaN (I use np.NaN)... but once i open the file, it shows a dash!.. any clue?  or i have to use Nan from other library?

**Comment by selik** [comment] 2020-07-22 15:06
Not a clue. Pandas uses Numpy's NaN value for floats, as far as I know. You shouldn't need to use a value from a different library. Someday soon I'll clear my task list and get a JMP trial to investigate these things.

**Comment by alfred-b-chan** [comment] 2020-07-22 15:10
I got it!
![image](https://user-images.githubusercontent.com/68042738/88193608-d9436280-cc0b-11ea-926b-c5d0fa4b4918.png)

That's a bug on line 838..... .it is supposed to be a period but it's now a underscore.. 

as a matter of fact, once i update to a period, everything works fine (ie showing period for null value)

**Comment by selik** [comment] 2020-07-22 15:12
Awesome. Want to send a pull request? Please update the appropriate test, if so.

**Comment by selik** [comment] 2020-07-22 15:17
XPT-format and IEEE support so many NaN possible values, but Python / NumPy only uses 1 value. Judging from the IBM-to-IEEE code, it looks like a leading underscore is a valid NaN value. You're saying that the leading period is preferable in the display?

**Comment by alfred-b-chan** [comment] 2020-07-22 15:19
this is in compliance with sas standard.  if it's missing (or null), it would show a period.

https://communities.sas.com/t5/SAS-Communities-Library/How-to-select-MISSING-SPACE-and-NULL-values-in-SAS-Customer/ta-p/242234

**Comment by selik** [comment] 2020-07-22 15:30
Sounds good to me. The section in the XPORT format specification document lists `._` first, but it makes sense that a plain `.` representation is the default.

```
Missing values are written out with the first byte (the exponent) indicating
the proper missing values. All subsequent bytes are 0x00. The first byte is:
type byte
 ._ 0x5f
 . 0x2e
 .A 0x41
 .B 0x42
 ....
 .Z 0x5a 
```

**Comment by selik** [comment] 2020-07-22 15:34
> flexibility to choose what to populate when null

That's going to be trickier, as it'll complicate the API. We could add a parameter to `dump`/`dumps`, but that'd change all NaNs. Since XPT allows 28 possible NaN values, each could be different. How would we represent them in Python, before writing out XPT?

**Comment by alfred-b-chan** [comment] 2020-07-22 15:50
hmm.. then pls let me know once the fix is up...   it's fine as long as it's not an underscore but a period

**Comment by selik** [comment] 2021-11-01 08:20
@LECARROU I'll be working on this project over the winter holidays

**Comment by selik** [comment] 2021-12-25 10:29
@alfred-b-chan @LECARROU I believe this is fixed in the latest version on PyPI. I'm also adding the SAS "Special Missing Values" feature to allow writing `._`, `.A`, `.B`, ..., `.Z`.

**Closed by selik** 2021-12-25 10:29 UTC
Labels: Could not reproduce
