### ISSUE TITLE
ds=xport.Dataset(df, name='MAX8CHRS', label='Up to 40!')  about "name" and "label" variable

### ISSUE THREAD

**Issue by lishuaiyin02** [selik/xport#87] opened 2022-01-28 09:04 UTC
Hi,Blogger，I wish to consult you on a few questions.
First, I want to the name above 8 characters, and labels above 40 characters. Can I do it？
Second, if I want to let the label variable become chinese, for example : xport.Dataset(df, name='MAX8CHRS', label='我我我'), what can I do to achieve it. By the way, I find in xport=3.2.1and pandas=1.0.3 the label is a description for dataset, however, in xport=3.5.0 and pandas=1.3.5 the label add every column.
I want to achieve as follow:
![image](https://user-images.githubusercontent.com/43161391/151516805-4d06110d-e4b7-4132-8a4a-43aca3e4a40f.png)

Third, I want to add labels for every column, I find I can use as below:
for k, v in ds.items():
    **v.label = k.title()**
    if v.dtype == 'object':
        v.format = '$CHAR20.'
    else:
        v.format = '10.2'

however,  I find v.label only is English characters, I want to let it become Chinese characters, for example:
for k, v in ds.items():
    **v.label = "您您您"**
    if v.dtype == 'object':
        v.format = '$CHAR20.'
    else:
        v.format = '10.2'
the result picture as follow:
![image](https://user-images.githubusercontent.com/43161391/151517543-a4324464-97c1-411b-8a02-b55d80ca4b7a.png)

Now,I am use  xport=3.2.1and pandas=1.0.3 and write use xport.v56.dump(ds, f)
Please help me !  Thank you very much!

Because I am a Chinese developer, my English is poor, so there may be errors in the expression. Please forgive me.

**Comment by gaineleanor** [comment] 2022-02-03 01:51
你好 
因为原来版本的编码问题需要自己计算长度. 

可以加好友吗. 同为中文开发者. 
微信  rock_guo

**Comment by selik** [comment] 2022-02-03 09:24
This is a duplicate of #75

**Closed by selik** 2022-02-03 09:24 UTC

**Comment by selik** [comment] 2022-02-03 09:35
Note that #89 may implement what you want.
