### ISSUE TITLE
Field names cannot start with an underscore: '_STATE'

### ISSUE THREAD

**Issue by m1ngle** [selik/xport#52] opened 2020-07-31 04:02 UTC
I'm attempting to read the Behavioral Risk Factor Surveillance System (BRFSS) report from the CDC. When I attempt to read it in I get ValueError: Field names cannot start with an underscore: '_STATE'. The obvious solution to me is to remove the underscore but then I get either ValueError: 256 is not a valid VariableType or 0 is not a valid VariableType

**Comment by selik** [comment] 2020-07-31 04:09
Can you link me to the file you're trying to read?

**Comment by m1ngle** [comment] 2020-07-31 04:15
Of course! https://www.cdc.gov/brfss/annual_data/2018/files/LLCP2018XPT.zip

**Comment by m1ngle** [comment] 2020-08-01 03:16
Just in case you were working on this over the weekend, the CDC also provided this as an ASC file which I was able to open as a csv. Thanks for looking into this.

**Comment by selik** [comment] 2020-11-09 04:17
Oh, hey, I kinda let this one slip off my radar. You've probably moved past this by now, but ... mind sharing the full traceback?

**Comment by proVizor-care** [comment] 2021-06-01 19:01
Hi,  I'm having the same issue with exactly the same BRFSS 2018 file.  I tried your suggestion to upload the ASC file as a CSV, which imported the file as only one column.  I may be able to sort it out with R.  Nonetheless, as you requested above, here is the traceback:  (It shouldn't make any difference, but I'm pulling the XPT file from my Google Drive.)

Looking forward to your guidance.

ValueError                                Traceback (most recent call last)
<ipython-input-13-550fc9b9f990> in <module>()
      1 with open('/content/drive/MyDrive/Colab/BRFSS - 2018/LLCP2018XPT.zip (Unzipped Files) (1)/LLCP2018.XPT ', 'rb') as file:
----> 2   library = xport.v56.load(file)

6 frames
/usr/lib/python3.7/collections/__init__.py in namedtuple(typename, field_names, rename, defaults, module)
    368     for name in field_names:
    369         if name.startswith('_') and not rename:
--> 370             raise ValueError('Field names cannot start with an underscore: '
    371                              f'{name!r}')
    372         if name in seen:

ValueError: Field names cannot start with an underscore: '_STATE'

**Comment by selik** [comment] 2021-06-01 20:29
That's frustrating. Looks like we can't use `namedtuple` in that situation. Thanks for sharing the traceback. I'll have to avoid use of `namedtuple` to enable reading that file.

**Comment by proVizor-care** [comment] 2021-06-01 21:33
Thanks for your prompt response.  I have no idea if resolving this is on your critical path, but I think I have another solution.  I'm not exactly fluent in SAS, but I can clunk my way through.  I'll import it into SAS and export from their as a CSV file.  It's been a couple of years, but I should be able to pull that off.  I'll let you know.  Thanks

**Comment by selik** [comment] 2021-06-01 21:37
If you have SAS or SAS Viewer, use that to export as CSV. Much safer than using this clunky tool. This project was intended to be available for people reading SAS files who don't have access to any official SAS products. SAS Viewer is free for Windows, so I thought only Mac and Linux users would want to use this project.

**Comment by selik** [comment] 2021-12-25 10:05
Digging in, it looks like I can trivially remove the `namedtuple` usage.

**Closed** 2021-12-25 10:11 UTC
