### ISSUE TITLE
xport.ParseError : header

### ISSUE THREAD

**Issue by tkazi** [selik/xport#13] opened 2017-09-05 15:59 UTC
Hi,

I am able to read some xpt files correctly, but for some files with the same code I am getting the following error:

**xport.ParseError: header -- expected b'HEADER RECORD*******LIBRARY HEADER RECORD!!!!!!!' got  b'STUDYID,DOMAIN,USUBJID,SUBJID,RFSTDTC,RFENDTC,RF'** 

The latter part of the error after "got" are the column names in my .xpt file. 

I am wondering if this has to do with the xpt file being generated in a newer version of SAS? If so, please advise how best to go around this issue. 

Thanks!

**Comment by selik** [comment] 2017-09-05 22:23
It's possible that the XPT format has changed. Could you tell me what version of SAS was used to create the XPT file?

**Comment by selik** [comment] 2017-09-05 22:30
Also, can you open the file in a plain text editor, like Notepad (on Windows) or TextEdit (on Mac) and share what the first several lines look like? Many of the lines might look like gibberish binary, but there will be some useful information.

**Comment by jasontowens** [comment] 2018-10-15 01:43
ÐÏà¡±á                >  þÿ	                         ^      þÿÿÿ       ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿR o o t   E n t r y                                               ÿÿÿÿÿÿÿÿ                                /
¬òÔO   €      S U B S E T S                                                    ÿÿÿÿ                          €ÞWòÔ /
¬òÔ            C o n t e n t s                                                   ÿÿÿÿÿÿÿÿÿÿÿÿ                                    '   ÙE      1                                                                ÿÿÿÿ                          pnKRòÔ /
¬òÔ            J   ýÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ"   #   $   %   N   ÿÿÿÿ(   )   *   +   ,   -   .   /   0   1   2   3   4   5   6   7   8   9   :   ;   <   =   >   ?   @   A   B   C   D   E   F   G   H   I   þÿÿÿK   þÿÿÿþÿÿÿP   M   !   Q   R   S   T   U   þÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿR o o t   E n t r y                                               ÿÿÿÿÿÿÿÿ                               Àô÷öòÔb   @)      S U B S E T S                                                    ÿÿÿÿ                          €ÞWòÔÀô÷öòÔ            C o n t e n t s                                                   ÿÿÿÿÿÿÿÿÿÿÿÿ                                       3F      1                                                                 ÿÿÿÿÿÿÿÿ                       pnKRòÔÀô÷öòÔ            ÿÿÿÿÿÿÿÿ]   ýÿÿÿ            	   
         
                                                             &   "   #   $   %   `   V   ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿQ   R   S   T   _   ÿÿÿÿW   X   Y   Z   [   þÿÿÿþÿÿÿ\   c   d   a   P   !   þÿÿÿe   f   g   h   i   j   þÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ Gen5ExperimentID    ÿÿ   CExpTemplateDoc Gen5ExpTemplateID                                  SINGLE      ç    ÿÿ  
 CProtocDoc      ÿÿ  
 CMethodDoc         ÿÿ   CPlateDescrParam  ÿÿ   CPromptParam   Prompt 1        	€   Prompt 2        	€   Prompt 3        	€   Prompt 4        	€   Prompt 5        	€   Prompt 6           Æ Ž×#å@ÿÿ   CPlateLayout        ÿÿ   CPanel   GENGenericNoneÿ       ÿÿ   CIdentifierConfig BLK         ÿÿ   CConcDil  ÿÿÿÿÿÿïÿ   ÿÿ  	 CLocation         €        €        €        €        €        €        €              €ÿÿ     BLK                    CTL                 @ €          €  ÿÿÿÿÿÿïÿ   €                    €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  SPL            ¦Êð      SPLC            ÀÀÀ      STD                              Name 1€zŸ×#å@                1€zŸ×#å@     K    ÿÿ  CAuditTrailEventDescr_String    Plate LayoutUser  ÿÿ   CBaseDeviceParameters       040.92â  
  ( 00000 00007130722E00001396 WELL PLATE  ÿÿÿÿÿÿÿÿ000062.09.1000072.08.12  041.02   0   
            0   
            0  100000     Î041.07      ÂÂÂÂÂÂ,¼ 
1 00   |040.98  2 
 d 0ÿÿÿÿÿÿ   041.01  ÿÿÿÿ00  0 d,0   011          00000   041.02ÿÿÿÿ    041.02ÿÿÿÿ å  00000     |040.98  d 
 d 0ÿÿÿÿÿÿ   041.01  ÿÿÿÿ00  0 d,0   011          00000   041.02ÿÿÿÿ    041.02ÿÿÿÿ ÿÿÿÿ  00000     |040.98  d 
 d 0ÿÿÿÿÿÿ   041.01  ÿÿÿÿ00  0 d,0   011          00000   041.02ÿÿÿÿ    041.02ÿÿÿÿ ÿÿÿÿ  00000     |040.98  d 
 d 0ÿÿÿÿÿÿ   041.01  ÿÿÿÿ00  0 d,0   011          00000   041.02ÿÿÿÿ    041.02ÿÿÿÿ ÿÿÿÿ  00000     |040.98  d 
 d 0ÿÿÿÿÿÿ   041.01  ÿÿÿÿ00  0 d,0   011          00000   041.02ÿÿÿÿ    041.02ÿÿÿÿ ÿÿÿÿ  00000     |040.98  d 
 d 0ÿÿÿÿÿÿ   041.01  ÿÿÿÿ00  0 d,0   011          00000   041.02ÿÿÿÿ    041.02ÿÿÿÿ ÿÿÿÿ  00000  017   
      è    0       :.         041.01    10  000     040.92Ñ„040.180  00                0 d, 
 d  0 ÿÿà 0

**Comment by jasontowens** [comment] 2018-10-15 01:48
ÐÏà¡±á                >  þÿ	                         ^      þÿÿÿ       ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿR o o t   E n t r y                                               ÿÿÿÿÿÿÿÿ                                /
¬òÔO   €      S U B S E T S                                                    ÿÿÿÿ                          €ÞWòÔ /
¬òÔ            C o n t e n t s                                                   ÿÿÿÿÿÿÿÿÿÿÿÿ                                    '   ÙE      1                                                                ÿÿÿÿ                          pnKRòÔ /
¬òÔ            J   ýÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ"   #   $   %   N   ÿÿÿÿ(   )   *   +   ,   -   .   /   0   1   2   3   4   5   6   7   8   9   :   ;   <   =   >   ?   @   A   B   C   D   E   F   G   H   I   þÿÿÿK   þÿÿÿþÿÿÿP   M   !   Q   R   S   T   U   þÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿR o o t   E n t r y                                               ÿÿÿÿÿÿÿÿ                               Àô÷öòÔb   @)      S U B S E T S                                                    ÿÿÿÿ                          €ÞWòÔÀô÷öòÔ            C o n t e n t s                                                   ÿÿÿÿÿÿÿÿÿÿÿÿ                                       3F      1                                                                 ÿÿÿÿÿÿÿÿ                       pnKRòÔÀô÷öòÔ            ÿÿÿÿÿÿÿÿ]   ýÿÿÿ            	   
         
                                                             &   "   #   $   %   `   V   ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿQ   R   S   T   _   ÿÿÿÿW   X   Y   Z   [   þÿÿÿþÿÿÿ\   c   d   a   P   !   þÿÿÿe   f   g   h   i   j   þÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ Gen5ExperimentID    ÿÿ   CExpTemplateDoc Gen5ExpTemplateID                                  SINGLE      ç    ÿÿ  
 CProtocDoc      ÿÿ  
 CMethodDoc         ÿÿ   CPlateDescrParam  ÿÿ   CPromptParam   Prompt 1        	€   Prompt 2        	€   Prompt 3        	€   Prompt 4        	€   Prompt 5        	€   Prompt 6           Æ Ž×#å@ÿÿ   CPlateLayout        ÿÿ   CPanel   GENGenericNoneÿ       ÿÿ   CIdentifierConfig BLK         ÿÿ   CConcDil  ÿÿÿÿÿÿïÿ   ÿÿ  	 CLocation         €        €        €        €        €        €        €              €ÿÿ     BLK                    CTL                 @ €          €  ÿÿÿÿÿÿïÿ   €                    €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                   €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  €          €  ÿÿÿÿÿÿïÿ   €                  SPL            ¦Êð      SPLC            ÀÀÀ      STD                              Name 1€zŸ×#å@                1€zŸ×#å@     K    ÿÿ  CAuditTrailEventDescr_String    Plate LayoutUser  ÿÿ   CBaseDeviceParameters       040.92â  
  ( 00000 00007130722E00001396 WELL PLATE  ÿÿÿÿÿÿÿÿ000062.09.1000072.08.12  041.02   0   
            0   
            0  100000     Î041.07      ÂÂÂÂÂÂ,¼ 
1 00   |040.98  2 
 d 0ÿÿÿÿÿÿ   041.01  ÿÿÿÿ00  0 d,0   011          00000   041.02ÿÿÿÿ    041.02ÿÿÿÿ å  00000     |040.98  d 
 d 0ÿÿÿÿÿÿ   041.01  ÿÿÿÿ00  0 d,0   011          00000   041.02ÿÿÿÿ    041.02ÿÿÿÿ ÿÿÿÿ  00000     |040.98  d 
 d 0ÿÿÿÿÿÿ   041.01  ÿÿÿÿ00  0 d,0   011          00000   041.02ÿÿÿÿ    041.02ÿÿÿÿ ÿÿÿÿ  00000     |040.98  d 
 d 0ÿÿÿÿÿÿ   041.01  ÿÿÿÿ00  0 d,0   011          00000   041.02ÿÿÿÿ    041.02ÿÿÿÿ ÿÿÿÿ  00000     |040.98  d 
 d 0ÿÿÿÿÿÿ   041.01  ÿÿÿÿ00  0 d,0   011          00000   041.02ÿÿÿÿ    041.02ÿÿÿÿ ÿÿÿÿ  00000     |040.98  d 
 d 0ÿÿÿÿÿÿ   041.01  ÿÿÿÿ00  0 d,0   011          00000   041.02ÿÿÿÿ    041.02ÿÿÿÿ ÿÿÿÿ  00000  017   
      è    0       :.         041.01    10  000     040.92Ñ„040.180  00                0 d, 
 d  0 ÿÿà 0 
010ô  10 È   P x  000     È 1ÿÿ0 `000 1  ÃP1                        
Plate Size      
Plate Type  1   Reading Zone  1   
Measurement 1  13   Gain 1  1=   Optics Position 1  1¤   Actual Temperature  1   Step 1 Description ÿÿ   CPlateDataSetDescriptor 485,520ÿÿ   CNumericFormat               RFU            ðiø@
T° 485,520                                                                ÿÿÿÿ                                                                   ÿÿ      ð?  ÿÿ   CColorEffectGen5                        ð¿      ð¿  èóÿ $|½                                     ÿÿ   CTemperatureDataSetDescriptor 
T° 485,520ç€              °C   ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ  ÿÿÿÿÿÿÿÿ    ÿÿ   CDataReduction   ÿÿ   CBlankTransform     ÿÿ   CDataSetReference                 þÿÿÿ485,520                               RFU                            485,520ç€               RFU            ðiø@
T° 485,520                                                                                                                                      ÿÿ      ð?  é€                        ð¿      ð¿  èóÿ $|½                                          
Blank 485,520          Blank TransformationBlank Subtraction   1€zŸ×#å@ÿÿ   X-BLK        BLK                    ÿÿ   COutputDataDescriptorMatrix         LayoutLayout     ö€         LayoutLayout       English (US) ÿÿ   CDataDescriptor        Well ID    þÿ         <     ø    È          ñ Arial 0û =Ó·fDÓ·fPÝ"¬þ‹„†m       ó  ù€        Name    þÿ         <     ø    È          ñ Arial 0û =Ó·fDÓ·fPÝ"¬þ‹„†m       ó                  ÿÿÿÿ  ÿÿÿÿ                ÿÿÿÿ   ÿÿEnglish (US) ù€        Well ID    þÿ         <     ø    È          ñ Arial 0û =Ó·fDÓ·fPÝ"¬þ‹„†m       ó  ù€        Name    þÿ         <     ø    È          ñ Arial 0û =Ó·fDÓ·fPÝ"¬þ‹„†m       ó                  ÿÿÿÿ  ÿÿÿÿ                ÿÿÿÿ   ÿÿÿÿ   COutputDataDescriptorStatsTable        Well IDsWell IDs     þ€        Well IDsWell IDs       English (US) ù€        Well ID    þÿ         <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€        Name    þÿ         <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð                                   ÿÿÿÿÿÿÿÿ    English (US) ù€        Well ID    þÿ         <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€        Name    þÿ         <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð                                   ÿÿÿÿÿÿÿÿ    ö€         485,520485,520      ö€         485,520485,520        English (US) ù€    485,520    485,520   þÿ        <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð                  ÿÿÿÿ  ÿÿÿÿ                ÿÿÿÿ   ÿÿEnglish (US) ù€    485,520    485,520   þÿ        <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð                  ÿÿÿÿ  ÿÿÿÿ                ÿÿÿÿ   ÿÿþ€        485,520485,520      þ€        485,520485,520        English (US) ù€        Well ID    þÿ         <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€        Name    þÿ         <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€        Well    þÿ         <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€    485,520    485,520             <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€    485,520    485,520            <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€    485,520    485,520            <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€    485,520    485,520            <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€    485,520    485,520            <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð                                   ÿÿÿÿÿÿÿÿ    English (US) ù€        Well ID    þÿ         <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€        Name    þÿ         <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€        Well    þÿ         <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€    485,520    485,520             <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€    485,520    485,520            <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€    485,520    485,520            <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€    485,520    485,520            <     ø    È          ð Arial 0û =Ó·fDÓ·fPÝ"¬þ‹€†m       ð  ù€  

**Comment by jasontowens** [comment] 2018-10-15 01:58
I have the same error as him. Just posting the text like you asked.

**Comment by selik** [comment] 2018-10-15 02:17
Gotcha. I didn't intend for you to post it here, but to email me with an attachment. No virus please ;-)

**Comment by selik** [comment] 2020-04-21 05:41
Closing as a potential duplicate of #10

**Closed by selik** 2020-04-21 05:41 UTC
